# This file defines locally all the configurations values that are required to run the project.

python:
#    binary: /opt/python3.13/bin/python3.13
    venv_path: .venv

paths:
    rvl_csv: data/raw/rvl_documents.csv # only store rvl document ids and labels
    clip_model: models/clip-vit-base

services:
    prediction_api:
        port: 8000
        expose_on_host: True
    mlflow:
        port: 5000
        expose_on_host: True
    auth:
        port: 7000
        expose_on_host: True
    streamlit:
        port: 8501
        expose_on_host: True
    prometheus:
        port: 9090
        expose_on_host: True
    grafana:
        port: 3000
        expose_on_host: True
    docker_compose:
        subnetwork: 72.20.0.0/16
