# this file is to be configured before running prepare.sh script
# would it be modified afterwards, it is highly recommended to rerun prepare.sh script
paths:
    rvl_csv: data/rvl_documents.csv # only store rvl document ids and labels
    to_ingest: data/to_ingest
    rejected: data/rejected
    raw: data/raw
    processed: data/processed
    models: models
    clip_model: models/clip-vit-base
    alternative_cdip_images_docker: mock_data/IIT-CDIP/images
    alternative_cdip_images_local: ../ds-project/mai25_bds_extraction/data/raw/IIT-CDIP/images

settings:
    locally_run: false # false in docker-compose / true for local (dev & tests)
    log_level: INFO # one of DEBUG, INFO, WARNING, ERROR 
    primarly_use_alternative_cdip_images: true

host_exposed_ports:
# open services
  streamlit: 64400
  predict: 64401

# authentication
#  auth: 64421

# orchestration and db
#   airflow-apiserver: 40641
#   flower: 40649
#   mlflow: 40642
#   postgres: 40643
#   pgadmin: 40644
#   redis: 40645

# atomic services
#   extract-text: 64411
#   process-text: 64412
#   process-image: 64413
#   compute-clip-embeddings: 64414
#   train: 64415

# monitoring
#   prometheus: 64160
#   grafana: 64161
#   cadvisor: 64162
#   dsdc-postgres-exporter: 64163
#   mlflow-postgres-exporter: 64164
#   airflow-postgres-exporter: 64165
