{
 "title": "Airflow DAG & Task Stats",
 "refresh": "30s",
 "panels": [
  {
   "title": "Total DAG Runs (Success)",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(dags_success)" }
   ]
  },
  {
   "title": "Total DAG Runs (Failed)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(dags_failed)" }
   ]
  },
  {
   "title": "Running DAGs",
   "type": "stat",
   "gridPos": { "x": 0, "y": 3, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(dags_running)" }
   ]
  },
  {
   "title": "DAG Avg Duration (Last 10)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 3, "w": 6, "h": 3 },
   "targets": [
    { "expr": "avg(dags_avg_duration_last_10)" }
   ]
  },
  {
   "title": "Total DAG Executions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 6, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(dags_total_runs)" }
   ]
  },
  {
   "title": "Total Task Successes",
   "type": "stat",
   "gridPos": { "x": 0, "y": 9, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(tasks_success)" }
   ]
  },
  {
   "title": "Total Task Failures",
   "type": "stat",
   "gridPos": { "x": 6, "y": 9, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(tasks_failed)" }
   ]
  },
  {
   "title": "Running Tasks",
   "type": "stat",
   "gridPos": { "x": 0, "y": 12, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(tasks_running)" }
   ]
  },
  {
   "title": "Task Avg Duration (Last 10)",
   "type": "stat",
   "gridPos": { "x": 6, "y": 12, "w": 6, "h": 3 },
   "targets": [
    {
     "expr": "avg(tasks_avg_duration_last_10)"
    }
   ]
  },
  {
   "title": "Total Task Executions",
   "type": "stat",
   "gridPos": { "x": 0, "y": 15, "w": 6, "h": 3 },
   "targets": [
    { "expr": "sum(tasks_executions_count)" }
   ]
  }
 ]
}