{
 "title": "Infrastructure & Ressources",
 "refresh": "15s",
 "templating": {
  "list": [
   {
    "name": "container_filter",
    "query": "label_values(container_cpu_usage_seconds_total, name)"
   },
   { "name": "service_filter" }
  ]
 },
 "panels": [
  {
   "title": "Utilisation CPU par Conteneur",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 18, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total[1m])",
     "legendFormat": "total"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{mode=\"user\"}[1m])",
     "legendFormat": "user"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{mode=\"system\"}[1m])",
     "legendFormat": "system"
    }
   ]
  },
  {
   "title": "Santé des Services - airflow",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count(dags_success)" }
   ]
  },
  {
   "title": "Mémoire des Conteneurs",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    { "expr": "container_memory_usage_bytes", "legendFormat": "usage" },
    {
     "expr": "container_memory_working_set_bytes",
     "legendFormat": "working set"
    },
    {
     "expr": "container_memory_max_usage_bytes",
     "legendFormat": "max"
    }
   ]
  },
  {
   "title": "original documents",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dsdc_tables_row_count{table=\"original_documents\"}"
    }
   ]
  },
  {
   "title": "labels",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dsdc_tables_row_count{table=\"labels\"}"
    }
   ]
  },
  {
   "title": "Utilisation Disque",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "container_fs_usage_bytes{device=\"\"}",
     "legendFormat": "usage"
    },
    { "expr": "container_fs_limit_bytes", "legendFormat": "limit" }
   ]
  },
  {
   "title": "raw texts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dsdc_tables_row_count{table=\"raw_texts\"}"
    }
   ]
  },
  {
   "title": "processed texts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dsdc_tables_row_count{table=\"processed_texts\"}"
    }
   ]
  },
  {
   "title": "Trafic Réseau",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 18, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(container_network_receive_bytes_total[1m])",
     "legendFormat": "RX"
    },
    {
     "expr": "rate(container_network_transmit_bytes_total[1m])",
     "legendFormat": "TX"
    }
   ]
  },
  {
   "title": "processed images",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dsdc_tables_row_count{table=\"processed_images\"}"
    }
   ]
  },
  {
   "title": "embeddings",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "dsdc_tables_row_count{table=\"embeddings\"}"
    }
   ]
  }
 ]
}