{
 "title": "Performances Modèle ML",
 "refresh": "30s",
 "panels": [
  {
   "title": "Modèles Entraînés",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "trained_models_count_run_uuid" }
   ]
  },
  {
   "title": "Précision",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "best_val_accuracy_best_val_accuracy"
    }
   ]
  },
  {
   "title": "Temps d'Entraînement Moyen",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "average_training_time_average_training_time_seconds"
    }
   ]
  },
  {
   "title": "Temps d'Entraînement (10 Derniers)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "last_10_training_time_last_10_avg_training_time_seconds"
    }
   ]
  }
 ]
}