{
 "title": "Rapports DAGs Airflow",
 "refresh": "10s",
 "panels": [
  {
   "title": "État des DAGs",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(dags_success)", "legendFormat": "Success" },
    { "expr": "sum(dags_failed)", "legendFormat": "Failed" },
    { "expr": "sum(dags_running)", "legendFormat": "Running" }
   ]
  },
  {
   "title": "Tâches En Cours",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tasks_running)" }
   ]
  },
  {
   "title": "Tâches Réussies",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tasks_success)" }
   ]
  },
  {
   "title": "Tâches Échouées",
   "type": "stat",
   "gridPos": { "h": 4, "w": 7, "x": 17, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(tasks_failed)" }
   ]
  },
  {
   "title": "Durée Totale par DAG",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 4 },
   "targets": [
    { "expr": "dags_avg_duration_last_10", "legendFormat": "{{dag_id}}" }
   ]
  },
  {
   "title": "Durée Moyenne (10 Derniers DAGs)",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 10, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "dags_avg_duration_last_10", "legendFormat": "{{dag_id}}" }
   ]
  },
  {
   "title": "Exécutions de Tâches",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 11 },
   "targets": [
    { "expr": "tasks_executions", "legendFormat": "{{task_id}}" }
   ]
  }
 ]
}