apiVersion: v1
kind: Secret
metadata:
  name: auth-secret
  namespace: mlops
type: Opaque
stringData:
  jwt: change-me
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: mlops
spec:
  replicas: 1
  selector: { matchLabels: { app: auth } }
  template:
    metadata: { labels: { app: auth } }
    spec:
      containers:
        - name: auth
          image: YOUR_REGISTRY/auth-api:latest
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef: { name: auth-secret, key: jwt }
          ports: [{ containerPort: 7000 }]
