{
 "title": "MLOps - CLIP API",
 "panels": [
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum(clip_total_requests)" }
   ]
  },
  {
   "title": "Requests Rate (1m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum(rate(clip_total_requests[1m]))"
    }
   ]
  },
  {
   "title": "Latency p95 (5m)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(clip_request_latency_seconds_bucket[5m])) by (le))"
    }
   ]
  }
 ]
}