global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
  - job_name: 'postgres'
    static_configs:
      - targets: ['services-postgres-exporter-1:9187']
  