# This file defines locally all the configurations values that are required to run the project.

paths:
    clip_model: models/
    models: /opt/dsdc/models
    
logging:
    level: INFO

services:
    postgres:
        root_db_name: postgres #TODO: unlink in code
        dsdc_db_name: dsdc_db
        airflow_db_name: airflow

settings:
    primarly_use_alternative_cdip_images: true
    locally_run: false # false in docker-compose / true for local (dev & tests)
