# TODO : dynamic creation

paths:
    rvl_csv: /opt/dsdc/data/rvl_documents.csv # only store rvl document ids and labels
    to_ingest: /opt/dsdc/data/to_ingest
    rejected: /opt/dsdc/data/rejected
    raw: /opt/dsdc/data/raw
    processed: /opt/dsdc/data/processed
    models: /opt/dsdc/models
    alternative_cdip_images: /opt/dsdc/mock_data/IIT-CDIP/images

settings:
    locally_run: false
    primarly_use_alternative_cdip_images: true

services:
    postgres:
        root_db_name: postgres
        dsdc_db_name: dsdc_db
        airflow_db_name: airflow

logging:
  level: info